name: Auto Update AdBlock List

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  workflow_dispatch: # Allows manual execution

jobs:
  update-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download & Merge Lists
        run: |
          mkdir -p lists
          cd lists
          urls=(
            "https://adblock.ee/list.txt"
"https://cdn.jsdelivr.net/gh/DandelionSprout/adfilt@master/NorwegianList.txt"
"https://cdn.jsdelivr.net/gh/DandelionSprout/adfilt@master/SerboCroatianList.txt"
"https://cdn.jsdelivr.net/gh/dimisa-RUAdList/RUAdListCDN@main/lists/ruadlist.ubo.min.txt"
"https://cdn.jsdelivr.net/gh/easylist/ruadlist@master/cntblock.txt"
"https://cdn.jsdelivr.net/gh/EasyList-Lithuania/easylist_lithuania@master/easylistlithuania.txt"
"https://cdn.jsdelivr.net/gh/hufilter/hufilter@gh-pages/hufilter-ublock.txt"
"https://cdn.jsdelivr.net/gh/lassekongo83/Frellwits-filter-lists@swefilter/swefilter.min.txt"
"https://cdn.jsdelivr.net/gh/List-KR/List-KR@latest/filter-uBlockOrigin.txt"
"https://cdn.jsdelivr.net/gh/MasterKia/PersianBlocker@main/PersianBlocker.txt"
"https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/filters/annoyances.min.txt"
"https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/filters/annoyances-cookies.txt"
"https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/filters/annoyances-cookies.txt"
"https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/filters/badlists.txt"
"https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/filters/badware.min.txt"
"https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/filters/filters.min.txt"
"https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/filters/lan-block.txt"
"https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/filters/privacy.min.txt"
"https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/filters/quick-fixes.min.txt"
"https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/filters/unbreak.min.txt"
"https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/thirdparties/easylist.txt"
"https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/thirdparties/easylist-annoyances.txt"
"https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/thirdparties/easylist-chat.txt"
"https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/thirdparties/easylist-cookies.txt"
"https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/thirdparties/easylist-newsletters.txt"
"https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/thirdparties/easylist-notifications.txt"
"https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/thirdparties/easylist-social.txt"
"https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/thirdparties/easyprivacy.txt"
"https://cdn.statically.io/gh/dimisa-RUAdList/RUAdListCDN/main/lists/ruadlist.ubo.min.txt"
"https://cdn.statically.io/gh/easylist/ruadlist/master/cntblock.txt"
"https://cdn.statically.io/gh/EasyList-Lithuania/easylist_lithuania/master/easylistlithuania.txt"
"https://cdn.statically.io/gh/MasterKia/PersianBlocker/main/PersianBlocker.txt"
"https://cdn.statically.io/gh/MasterKia/PersianBlocker/main/PersianBlocker.txt"
"https://cdn.statically.io/gh/uBlockOrigin/uAssetsCDN/main/filters/annoyances.min.txt"
"https://cdn.statically.io/gh/uBlockOrigin/uAssetsCDN/main/filters/annoyances-cookies.txt"
"https://cdn.statically.io/gh/uBlockOrigin/uAssetsCDN/main/filters/annoyances-cookies.txt"
"https://cdn.statically.io/gh/uBlockOrigin/uAssetsCDN/main/filters/badlists.txt"
"https://cdn.statically.io/gh/uBlockOrigin/uAssetsCDN/main/filters/badware.min.txt"
"https://cdn.statically.io/gh/uBlockOrigin/uAssetsCDN/main/filters/filters.min.txt"
"https://cdn.statically.io/gh/uBlockOrigin/uAssetsCDN/main/filters/privacy.min.txt"
"https://cdn.statically.io/gh/uBlockOrigin/uAssetsCDN/main/filters/quick-fixes.min.txt"
"https://cdn.statically.io/gh/uBlockOrigin/uAssetsCDN/main/filters/unbreak.min.txt"
"https://cdn.statically.io/gh/uBlockOrigin/uAssetsCDN/main/thirdparties/easylist.txt"
"https://cdn.statically.io/gh/uBlockOrigin/uAssetsCDN/main/thirdparties/easylist-annoyances.txt"
"https://cdn.statically.io/gh/uBlockOrigin/uAssetsCDN/main/thirdparties/easylist-chat.txt"
"https://cdn.statically.io/gh/uBlockOrigin/uAssetsCDN/main/thirdparties/easylist-cookies.txt"
"https://cdn.statically.io/gh/uBlockOrigin/uAssetsCDN/main/thirdparties/easylist-newsletters.txt"
"https://cdn.statically.io/gh/uBlockOrigin/uAssetsCDN/main/thirdparties/easylist-notifications.txt"
"https://cdn.statically.io/gh/uBlockOrigin/uAssetsCDN/main/thirdparties/easylist-social.txt"
"https://cdn.statically.io/gh/uBlockOrigin/uAssetsCDN/main/thirdparties/easyprivacy.txt"
"https://cdn.statically.io/gl/DandelionSprout/adfilt/master/NorwegianList.txt"
"https://cdn.statically.io/gl/DandelionSprout/adfilt/master/SerboCroatianList.txt"
"https://curbengh.github.io/malware-filter/urlhaus-filter-ag-online.txt"
"https://curbengh.github.io/phishing-filter/phishing-filter.txt"
"https://easylist.to/easylistgermany/easylistgermany.txt"
"https://easylist-downloads.adblockplus.org/easylistgermany.txt"
"https://easylist-downloads.adblockplus.org/easylistitaly.txt"
"https://easylist-downloads.adblockplus.org/easylistspanish.txt"
"https://easylist-downloads.adblockplus.org/indianlist.txt"
"https://easylist-downloads.adblockplus.org/Liste_AR.txt"
"https://filters.adtidy.org/extension/ublock/filters/11.txt"
"https://filters.adtidy.org/extension/ublock/filters/13.txt"
"https://filters.adtidy.org/extension/ublock/filters/16.txt"
"https://filters.adtidy.org/extension/ublock/filters/18.txt"
"https://filters.adtidy.org/extension/ublock/filters/19.txt"
"https://filters.adtidy.org/extension/ublock/filters/2_without_easylist.txt"
"https://filters.adtidy.org/extension/ublock/filters/20.txt"
"https://filters.adtidy.org/extension/ublock/filters/21.txt"
"https://filters.adtidy.org/extension/ublock/filters/22.txt"
"https://filters.adtidy.org/extension/ublock/filters/224.txt"
"https://filters.adtidy.org/extension/ublock/filters/4.txt"
"https://filters.adtidy.org/extension/ublock/filters/7.txt"
"https://filters.adtidy.org/extension/ublock/filters/8.txt"
"https://filters.adtidy.org/extension/ublock/filters/9.txt"
"https://malware-filter.gitlab.io/phishing-filter/phishing-filter.txt"
"https://malware-filter.gitlab.io/phishing-filter/phishing-filter.txt"
"https://malware-filter.gitlab.io/urlhaus-filter/urlhaus-filter-ag-online.txt"
"https://malware-filter.gitlab.io/urlhaus-filter/urlhaus-filter-ag-online.txt"
"https://malware-filter.pages.dev/urlhaus-filter-ag-online.txt"
"https://phishing-filter.pages.dev/phishing-filter.txt"
"https://raw.githubusercontent.com/ABPindo/indonesianadblockrules/master/subscriptions/abpindo.txt"
"https://raw.githubusercontent.com/abpvn/abpvn/master/filter/abpvn_ublock.txt"
"https://raw.githubusercontent.com/AnXh3L0/blocklist/master/albanian-easylist-addition/Albania.txt"
"https://raw.githubusercontent.com/betterwebleon/slovenian-list/master/filters.txt"
"https://raw.githubusercontent.com/brave/adblock-lists/master/custom/is.txt"
"https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianList.txt"
"https://raw.githubusercontent.com/DandelionSprout/adfilt/master/SerboCroatianList.txt"
"https://raw.githubusercontent.com/dimisa-RUAdList/RUAdListCDN/main/lists/ruadlist.ubo.min.txt"
"https://raw.githubusercontent.com/easylist/EasyListHebrew/master/EasyListHebrew.txt"
"https://raw.githubusercontent.com/easylist/ruadlist/master/cntblock.txt"
"https://raw.githubusercontent.com/easylist/ruadlist/master/cntblock.txt"
"https://raw.githubusercontent.com/easylist/ruadlist/master/RuAdList-uBO.txt"
"https://raw.githubusercontent.com/EasyList-Lithuania/easylist_lithuania/master/easylistlithuania.txt"
"https://raw.githubusercontent.com/easylist-thailand/easylist-thailand/master/subscription/easylist-thailand.txt"
"https://raw.githubusercontent.com/finnish-easylist-addition/finnish-easylist-addition/gh-pages/Finland_adb.txt"
"https://raw.githubusercontent.com/lassekongo83/Frellwits-filter-lists/master/Frellwits-Swedish-Filter.txt"
"https://raw.githubusercontent.com/lassekongo83/Frellwits-filter-lists/swefilter/swefilter.min.txt"
"https://raw.githubusercontent.com/Latvian-List/adblock-latvian/master/lists/latvian-list.txt"
"https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock.txt"
"https://raw.githubusercontent.com/MasterKia/PersianBlocker/main/PersianBlocker.txt"
"https://raw.githubusercontent.com/olegwukr/polish-privacy-filters/master/anti-adblock.txt"
"https://raw.githubusercontent.com/tcptomato/ROad-Block/master/road-block-filters-light.txt"
"https://raw.githubusercontent.com/tomasko126/easylistczechandslovak/master/filters.txt"
"https://raw.githubusercontent.com/ukrainianfilters/lists/main/combined/uBO/uBO.txt"
"https://secure.fanboy.co.nz/fanboy-antifacebook.txt"
"https://secure.fanboy.co.nz/fanboy-cookiemonster_ubo.txt"
"https://secure.fanboy.co.nz/fanboy-social_ubo.txt"
"https://stanev.org/abp/adblock_bg.txt"
"https://ublockorigin.github.io/uAssets/filters/annoyances.txt"
"https://ublockorigin.github.io/uAssets/filters/annoyances-cookies.txt"
"https://ublockorigin.github.io/uAssets/filters/annoyances-cookies.txt"
"https://ublockorigin.github.io/uAssets/filters/badlists.txt"
"https://ublockorigin.github.io/uAssets/filters/badware.txt"
"https://ublockorigin.github.io/uAssets/filters/filters.txt"
"https://ublockorigin.github.io/uAssets/filters/lan-block.txt"
"https://ublockorigin.github.io/uAssets/filters/privacy.txt"
"https://ublockorigin.github.io/uAssets/filters/quick-fixes.txt"
"https://ublockorigin.github.io/uAssets/filters/unbreak.txt"
"https://ublockorigin.github.io/uAssets/thirdparties/easylist.txt"
"https://ublockorigin.github.io/uAssets/thirdparties/easylist-annoyances.txt"
"https://ublockorigin.github.io/uAssets/thirdparties/easylist-chat.txt"
"https://ublockorigin.github.io/uAssets/thirdparties/easylist-cookies.txt"
"https://ublockorigin.github.io/uAssets/thirdparties/easylist-newsletters.txt"
"https://ublockorigin.github.io/uAssets/thirdparties/easylist-notifications.txt"
"https://ublockorigin.github.io/uAssets/thirdparties/easylist-social.txt"
"https://ublockorigin.github.io/uAssets/thirdparties/easyprivacy.txt"
"https://ublockorigin.github.io/uAssetsCDN/filters/annoyances.min.txt"
"https://ublockorigin.github.io/uAssetsCDN/filters/annoyances-cookies.txt"
"https://ublockorigin.github.io/uAssetsCDN/filters/annoyances-cookies.txt"
"https://ublockorigin.github.io/uAssetsCDN/filters/badlists.txt"
"https://ublockorigin.github.io/uAssetsCDN/filters/badware.min.txt"
"https://ublockorigin.github.io/uAssetsCDN/filters/filters.min.txt"
"https://ublockorigin.github.io/uAssetsCDN/filters/lan-block.txt"
"https://ublockorigin.github.io/uAssetsCDN/filters/privacy.min.txt"
"https://ublockorigin.github.io/uAssetsCDN/filters/quick-fixes.min.txt"
"https://ublockorigin.github.io/uAssetsCDN/filters/unbreak.min.txt"
"https://ublockorigin.github.io/uAssetsCDN/thirdparties/easylist-annoyances.txt"
"https://ublockorigin.github.io/uAssetsCDN/thirdparties/easylist-chat.txt"
"https://ublockorigin.github.io/uAssetsCDN/thirdparties/easylist-cookies.txt"
"https://ublockorigin.github.io/uAssetsCDN/thirdparties/easylist-newsletters.txt"
"https://ublockorigin.github.io/uAssetsCDN/thirdparties/easylist-notifications.txt"
"https://ublockorigin.github.io/uAssetsCDN/thirdparties/easylist-social.txt"
"https://ublockorigin.pages.dev/filters/annoyances.min.txt"
"https://ublockorigin.pages.dev/filters/annoyances-cookies.txt"
"https://ublockorigin.pages.dev/filters/annoyances-cookies.txt"
"https://ublockorigin.pages.dev/filters/badlists.txt"
"https://ublockorigin.pages.dev/filters/badware.min.txt"
"https://ublockorigin.pages.dev/filters/filters.min.txt"
"https://ublockorigin.pages.dev/filters/lan-block.txt"
"https://ublockorigin.pages.dev/filters/privacy.min.txt"
"https://ublockorigin.pages.dev/filters/quick-fixes.min.txt"
"https://ublockorigin.pages.dev/filters/unbreak.min.txt"
"https://ublockorigin.pages.dev/thirdparties/easylist.txt"
"https://ublockorigin.pages.dev/thirdparties/easylist-annoyances.txt"
"https://ublockorigin.pages.dev/thirdparties/easylist-chat.txt"
"https://ublockorigin.pages.dev/thirdparties/easylist-cookies.txt"
"https://ublockorigin.pages.dev/thirdparties/easylist-newsletters.txt"
"https://ublockorigin.pages.dev/thirdparties/easylist-notifications.txt"
"https://ublockorigin.pages.dev/thirdparties/easylist-social.txt"
"https://www.void.gr/kargig/void-gr-filters.txt"
            # Add the rest of the URLs here...
          )

          for url in "${urls[@]}"; do
            curl -sL "$url" >> merged.txt || echo "# Failed to fetch: $url" >> errors.log
          done

          sort -u merged.txt -o merged.txt  # Remove duplicates

      - name: Commit & Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add merged.txt errors.log
          git commit -m "Auto-update adblock list" || echo "No changes to commit"
          git push
